version: "3.9"
services:
  config:
    image: nedbank-service-config:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "native"
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ./resources:/opt/config
  resource:
    image: nedbank-service-resourcebundle:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 9080
    ports:
      - "9080:9080"
    depends_on:
      config:
        condition: service_healthy
  sarb:
    image: nedbank-service-sarb:0.0.1-SNAPSHOT
    ports:
      - "9081:9081"
    environment:
      SERVER_PORT: 9081
  grafana:
    image: grafana/grafana:8.3.3-ubuntu
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
    - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
  prometheus:
    image: prom/prometheus:v2.32.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml

