version: "3.9"
services:
  config:
    image: nedbank-service-config:0.0.1-SNAPSHOT
  resource:
    image: nedbank-service-resourcebundle:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE: native
