---
encryption:
  key: 6zF6EVA2^eZRFBN!svJu2m57GJSYDdEy585+2%C?_JrbK*pCga5=yWLKXK!C-4shrNYGSV
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, refresh, info, bus-refresh, busenv, busrefresh
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:/opt/config
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
